apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
  annotations:
      storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  datastoreurl: "ds:///vmfs/volumes/vsan:url/"
