---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mc-backup-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: slow
