---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mc-world-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast
