---
apiVersion: v1
kind: Service
metadata:
  name: mc-enigmatica-server-service
  labels:
    app: mc-enigmatica-server
  namespace: minecraft-openshift
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: mc-enigmatica-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-enigmatica-server
  namespace: minecraft-openshift
  labels:
    app: mc-enigmatica-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-enigmatica-server
  template:
    metadata:
      labels:
        app: mc-enigmatica-server
    spec:
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: mc-world-claim
      - name: minecraft-backups
        persistentVolumeClaim:
          claimName: mc-backup-claim
      containers:
      - name: mc-enigmatica-server
        image: harbor.akirasoft.com/mvilliger/enigmatica:1.77g
        resources:
          limits:
            memory: 12Gi
            cpu: 2000m
          requests:
            memory: 11Gi
            cpu: 2000m
        env:
          - name: DEFAULT_OP
            value: 'Akirasoft'
          - name: MINECRAFT_EULA
            value: 'true'
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data/enigmatica2/world
          - name: minecraft-backups
            mountPath:  /data/enigmatica2/backups
